// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import "./globals.css";
import type { Metadata } from "next";
// import { Satoshi } from "@/assets/fonts/font";
import TanstackProvider from "@/components/layout/tanstackProvider";


export const metadata: Metadata = {
  title: "NUBIA | Write with ease",
  description: "Nubia is your personal writer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}