// import type { Metadata } from "next";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

// import { Satoshi } from "@/assets/fonts/font";
import TanstackProvider from "@/components/layout/tanstackProvider";
import LandingNavbar from "@/components/lib/navigation/landing_navbar";
import Footer from "@/components/landing-comps/footer";

export const metadata: Metadata = {
  title: "Goloka | Write with ease",
  description: "Goloka is your personal writer",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <TanstackProvider>
          <LandingNavbar />
          {children}
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
